server:
  port: 8761 # Port standard pour Eureka

spring:
  application:
    name: eventy-eureka-service

eureka:
  instance:
    hostname: localhost
  client:
    # Le serveur Eureka n'a pas besoin de s'enregistrer auprès de lui-même
    register-with-eureka: false 
    # Le serveur Eureka n'a pas besoin de récupérer la liste des clients
    fetch-registry: false
    service-url:
      # URL de la zone par défaut, utilisée par les clients pour se connecter
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka